spring.datasource.url=jdbc:postgresql://localhost:5432/stewy
spring.datasource.username=stewy
spring.datasource.password=krcgenk
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=stewy-secret-key-that-is-at-least-256-bits-long-for-hs256-algorithm
jwt.expiration-ms=86400000
