name: FE with bun

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fe-build:
    name: fe-build
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - name: install
        run: |
          cd ./stewy-fe
          bun install
      
      - name: build
        run: |
          cd ./stewy-fe
          bun run build